package com.brasa.tv.app.navigation
import androidx.compose.runtime.*
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.compose.*
import androidx.compose.ui.platform.LocalSoftwareKeyboardController
import kotlinx.coroutines.delay
import com.brasa.tv.BuildConfig
import com.brasa.tv.app.BrasaViewModel
import com.brasa.tv.core.di.AppContainer
import com.brasa.tv.feature.details.DetailsScreen
import com.brasa.tv.feature.home.HomeScreen
import com.brasa.tv.feature.home.CatalogScreen
import com.brasa.tv.feature.library.CollectionsScreen
import com.brasa.tv.feature.library.LibraryScreen
import com.brasa.tv.feature.pairing.PairingScreen
import com.brasa.tv.feature.player.PlayerScreen
import com.brasa.tv.feature.profiles.*
import com.brasa.tv.feature.search.SearchScreen
import com.brasa.tv.feature.server.ServerScreen
import com.brasa.tv.feature.startup.StartupScreen
import com.brasa.tv.feature.settings.SettingsScreen
import com.brasa.tv.feature.network.NetworkDiagnosticsScreen
import com.brasa.tv.feature.network.NetworkDiagnosticsViewModel
import com.brasa.tv.feature.update.*
object Routes{const val Startup="startup";const val Server="server";const val Pairing="pairing";const val Profiles="profiles";const val ProfilePin="profile-pin";const val Home="home";const val Catalog="catalog";const val Movies="movies";const val Series="series";const val Collections="collections";const val Search="search";const val Details="details";const val Player="player";const val Settings="settings";const val NetworkDiagnostics="network-diagnostics";const val Update="update"}
@Composable fun BrasaNavHost(container:AppContainer,previewMode:Boolean=false,previewPage:String="home",onExit:()->Unit={}){val nav=rememberNavController();val keyboard=LocalSoftwareKeyboardController.current;val currentEntry by nav.currentBackStackEntryAsState();val vm:BrasaViewModel=viewModel(factory=BrasaViewModel.Factory(container.repository,container.playback));val updateVm:UpdateViewModel=viewModel(factory=UpdateViewModel.Factory(container.updateRepository,container.settings,container.updatePreferences,container.http,container.context,container.apkValidator,container.packageInstaller));val permissionLauncher=rememberLauncherForActivityResult(ActivityResultContracts.StartActivityForResult()){updateVm.permissionReturned()};val state by vm.state.collectAsState();val updateState by updateVm.state.collectAsState();var startupUpdateRequired by remember{mutableStateOf(false)};val beginStartupUpdate={startupUpdateRequired=true;updateVm.check(true)};val previewRoute=previewPage.takeIf{it in setOf(Routes.Server,Routes.Pairing,Routes.Profiles,Routes.ProfilePin,Routes.Home,Routes.Movies,Routes.Series,Routes.Collections,Routes.Search,Routes.Details,Routes.Player,Routes.Settings,Routes.Update)}?:Routes.Home;LaunchedEffect(previewMode,previewRoute){if(previewMode&&BuildConfig.DEBUG)vm.enablePreview(previewRoute)};LaunchedEffect(currentEntry?.destination?.route){keyboard?.hide();delay(180);keyboard?.hide()};LaunchedEffect(startupUpdateRequired,updateState,currentEntry?.destination?.route){if(!startupUpdateRequired||state.previewMode)return@LaunchedEffect;val route=currentEntry?.destination?.route;when(updateState){UpdateUiState.UpToDate,is UpdateUiState.Installed->{startupUpdateRequired=false;if(route==Routes.Startup||route==Routes.Server||route==Routes.Update)nav.navigate(Routes.Profiles){popUpTo(Routes.Startup){inclusive=true};launchSingleTop=true}};is UpdateUiState.Available,is UpdateUiState.Error,is UpdateUiState.Downloading,is UpdateUiState.Validating,is UpdateUiState.Ready,is UpdateUiState.PermissionRequired,is UpdateUiState.Installing->{if(route==Routes.Startup||route==Routes.Server)nav.navigate(Routes.Update){launchSingleTop=true}};else->{}}};NavHost(navController=nav,startDestination=if(previewMode&&BuildConfig.DEBUG)previewRoute else Routes.Startup){
composable(Routes.Startup){LaunchedEffect(Unit){vm.restore{paired->if(paired)beginStartupUpdate()else nav.navigate(Routes.Server){popUpTo(Routes.Startup){inclusive=true}}}};StartupScreen(if(state.loading)"Preparando sua experiência…" else "Conectando à sua biblioteca…")}
composable(Routes.Server){LaunchedEffect(Unit){if(!state.previewMode)vm.restore{paired->if(paired)beginStartupUpdate()}};ServerScreen(state,container){address->vm.connect(address){paired->if(paired)beginStartupUpdate()else nav.navigate(Routes.Pairing)}}}
composable(Routes.Pairing){PairingScreen(state,onStart={vm.startPairing(it){startupUpdateRequired=true;updateVm.check(true);nav.popBackStack()}},onBack={vm.stopPairing();nav.popBackStack()})}
composable(Routes.Profiles){ProfileScreen(state,onLoad={if(!state.previewMode)vm.loadProfiles{}},onSelect={profile->if(profile.hasPin&&profile.kind!="kids"){vm.prepareProfile(profile);nav.navigate(Routes.ProfilePin)}else vm.chooseProfile(profile){nav.navigate(Routes.Home){popUpTo(Routes.Profiles){inclusive=true};launchSingleTop=true}}},onExit=onExit)}
composable(Routes.ProfilePin){ProfilePinScreen(state,onVerify={pin->vm.verifyPin(pin){valid->if(valid)state.profile?.let{profile->vm.chooseProfile(profile){nav.navigate(Routes.Home){popUpTo(Routes.Profiles){inclusive=true};launchSingleTop=true}}}}},onBack={nav.popBackStack()})}
composable(Routes.Home){LaunchedEffect(state.profile?.id){if(!state.previewMode&&state.profile!=null){vm.refreshHome();vm.refreshCatalog();if(updateState===UpdateUiState.Idle)updateVm.check(false)}};LaunchedEffect(updateState){if(!state.previewMode&&updateState is UpdateUiState.Available&&nav.currentDestination?.route==Routes.Home)nav.navigate(Routes.Update)};HomeScreen(state,onItem={vm.select(it);nav.navigate(Routes.Details)},onPlay={item->vm.select(item);if(item.type=="series")nav.navigate(Routes.Details)else vm.loadPlayback(item){nav.navigate(Routes.Player)}},onPrefetch=vm::prefetchPlaybackMetadata,onSearch={nav.navigate(Routes.Search)},onMovies={nav.navigate(Routes.Movies)},onSeries={nav.navigate(Routes.Series)},onCollections={nav.navigate(Routes.Collections)},onProfiles={if(!state.previewMode)nav.navigate(Routes.Profiles)},onSettings={if(!state.previewMode)nav.navigate(Routes.Settings)},onSeeMore={vm.selectRow(it);nav.navigate(Routes.Catalog)},onRefresh=vm::refreshHome)}
composable(Routes.Catalog){CatalogScreen(state,onItem={vm.select(it);nav.navigate(Routes.Details)},onBack={nav.popBackStack()})}
composable(Routes.Movies){LibraryScreen(state,"movie",onItem={vm.select(it);nav.navigate(Routes.Details)},onHome={nav.navigate(Routes.Home){popUpTo(Routes.Home)}},onMovies={},onSeries={nav.navigate(Routes.Series)},onCollections={nav.navigate(Routes.Collections)},onSearch={nav.navigate(Routes.Search)},onProfiles={nav.navigate(Routes.Profiles)},onRefresh=vm::refreshCatalog)}
composable(Routes.Series){LibraryScreen(state,"series",onItem={vm.select(it);nav.navigate(Routes.Details)},onHome={nav.navigate(Routes.Home){popUpTo(Routes.Home)}},onMovies={nav.navigate(Routes.Movies)},onSeries={},onCollections={nav.navigate(Routes.Collections)},onSearch={nav.navigate(Routes.Search)},onProfiles={nav.navigate(Routes.Profiles)},onRefresh=vm::refreshCatalog)}
composable(Routes.Collections){CollectionsScreen(state,onItem={vm.select(it);nav.navigate(Routes.Details)},onHome={nav.navigate(Routes.Home){popUpTo(Routes.Home)}},onMovies={nav.navigate(Routes.Movies)},onSeries={nav.navigate(Routes.Series)},onSearch={nav.navigate(Routes.Search)},onProfiles={nav.navigate(Routes.Profiles)},onRefresh=vm::refreshCatalog)}
composable(Routes.Search){SearchScreen(state,onSearch=vm::search,onItem={vm.select(it);nav.navigate(Routes.Details)},onMovies={nav.navigate(Routes.Movies)},onSeries={nav.navigate(Routes.Series)},onCollections={nav.navigate(Routes.Collections)},onRefresh=vm::refreshCatalog,onBack={nav.popBackStack()})}
composable(Routes.Details){DetailsScreen(state,onPlay={vm.loadPlayback(it){nav.navigate(Routes.Player)}},onPrefetch=vm::preloadPlayback,onCancelPreload=vm::cancelPreload,onFavorite=vm::toggleFavorite,onBack={nav.popBackStack()})}
composable(Routes.Player){PlayerScreen(state,container,onProgress=vm::saveProgress,onPlaybackFallback=vm::fallbackPlayback,onRemoteSeek=vm::seekPlayback,onRetry={state.selected?.let{vm.loadPlayback(it){}}},onNext={vm.select(it);vm.loadPlayback(it){}},onBack={vm.cancelPlaybackPreparation();nav.popBackStack()})}
composable(Routes.Settings){SettingsScreen(state,container.settings,lastUpdateCheckAt=updateVm.lastCheckAt(),onUpdates={updateVm.check(true);nav.navigate(Routes.Update)},onNetworkDiagnostics={nav.navigate(Routes.NetworkDiagnostics)},onScanLibrary=vm::scanLibrary,onProfiles={nav.navigate(Routes.Profiles)},onClearCache=vm::clearPlaybackCache,onLoadCache=vm::refreshCacheUsage,onForget={vm.forget{nav.navigate(Routes.Server){popUpTo(0)}}},onBack={nav.popBackStack()})}
composable(Routes.NetworkDiagnostics){val networkVm:NetworkDiagnosticsViewModel=viewModel(factory=NetworkDiagnosticsViewModel.Factory(container.repository,container.networkAccess));val networkState by networkVm.state.collectAsState();NetworkDiagnosticsScreen(networkState,networkVm::load,networkVm::selectProfile,networkVm::runTest,networkVm::cancel){nav.popBackStack()}}
composable(Routes.Update){val visibleUpdateState=if(state.previewMode)UpdateUiState.Available(UpdateManifest(packageName="com.brasa.tv",versionCode=42,versionName="2.4.0",sizeBytes=28_400_000,releaseNotes=listOf("Navegação mais fluida na TV","Player com carregamento aprimorado","Novo modo de atualização local")))else updateState;UpdateScreen(visibleUpdateState,onCheck={updateVm.check(true)},onDownload=updateVm::download,onCancel=updateVm::cancel,onInstall=updateVm::prepareInstall,onPermission={permissionLauncher.launch(updateVm.permissionIntent())},onBack={if(startupUpdateRequired){if(visibleUpdateState===UpdateUiState.UpToDate||visibleUpdateState is UpdateUiState.Installed){startupUpdateRequired=false;nav.navigate(Routes.Profiles){popUpTo(Routes.Server){inclusive=true};launchSingleTop=true}}}else{updateVm.defer();nav.popBackStack()}},required=startupUpdateRequired)}
}}
