import { getActiveProfileRecord, initializeProfileService, listProfiles, switchActiveProfile, verifyProfilePin } from "../services/profile-service.js";

export function getProfiles(){return listProfiles();}
export function getActiveProfile(){return getActiveProfileRecord();}
export async function setActiveProfile(profileId){return switchActiveProfile(profileId);}
export function isKidsProfile(profile=getActiveProfile()){return profile?.kind==="kids";}
export function filterContentByProfile(content,profile=getActiveProfile()){const items=Array.isArray(content)?content:[];return isKidsProfile(profile)?items.filter((item)=>item?.kids===true):[...items];}
export async function initializeProfiles(root=document){await initializeProfileService();bindProfileControls(root);updateProfileControls(root);const active=getActiveProfile();if(active)return active;return openProfileSelector({initial:true});}
export function bindProfileControls(root=document){if(root.__brasaProfileControlsBound)return;root.__brasaProfileControlsBound=true;root.addEventListener("click",(event)=>{if(event.target.closest("[data-profile-switcher]"))openProfileSelector();});}
export function updateProfileControls(root=document){const profile=getActiveProfile();root.querySelectorAll("[data-profile-switcher]").forEach((control)=>{const name=control.querySelector("[data-profile-name]");const initials=control.querySelector("[data-profile-initials]");control.dataset.profileId=profile?.id||"";control.setAttribute("aria-label",profile?`Trocar perfil, atual: ${profile.name}`:"Escolher perfil");if(name)name.textContent=profile?.name||"Perfis";if(initials)initials.textContent=profile?.initials||"?";});window.lucide?.createIcons?.();}
export function openProfileSelector({initial=false}={}){const existing=document.querySelector(".profile-selector");if(existing)return existing.__promise||Promise.resolve(getActiveProfile());return new Promise((resolve)=>{const overlay=document.createElement("div");const profiles=getProfiles();const active=getActiveProfile();overlay.className="profile-selector";overlay.innerHTML=`<section class="profile-selector__dialog" role="dialog" aria-modal="true" aria-label="${initial?"Escolher perfil":"Trocar perfil"}"><p class="profile-selector__eyebrow">BRasa</p><h1>${initial?"Quem está assistindo?":"Trocar perfil"}</h1><p>Escolha quem vai usar o BRasa agora.</p><div class="profile-selector__list">${profiles.map((p)=>`<button class="profile-selector__card ${p.id===active?.id?"is-active":""}" type="button" data-profile-id="${p.id}"><span class="profile-selector__avatar profile-avatar--${p.avatar?.color||"blue"}">${p.initials}</span><strong>${p.name}</strong><small>${p.kind==="kids"?"Perfil infantil":"Perfil adulto"}</small></button>`).join("")}</div>${isKidsProfile(active)?"":`<a class="profile-selector__manage" href="${location.pathname.includes('/pages/')?'settings.html':'pages/settings.html'}#profiles">Gerenciar perfis</a>`}${initial?"":'<button class="profile-selector__cancel" type="button" data-profile-cancel>Cancelar</button>'}</section>`;const close=(value)=>{overlay.remove();resolve(value);};overlay.addEventListener("click",async(event)=>{const button=event.target.closest("[data-profile-id]");if(button){const next=profiles.find((p)=>p.id===button.dataset.profileId);if(next?.kind==="kids"&&!next.hasPin){alert("Configure um PIN para o perfil infantil em Gerenciar perfis antes de entrar.");return;}if(isKidsProfile(active)&&next?.kind==="adult"){const allowed=await requestExitPin(active);if(!allowed)return;}await setActiveProfile(next.id);updateProfileControls();close(next);location.reload();}if(event.target.closest("[data-profile-cancel]"))close(null);});overlay.addEventListener("keydown",(event)=>{if(event.key==="Escape"&&!initial)close(null);});document.body.appendChild(overlay);overlay.querySelector("[data-profile-id]")?.focus();});}
async function requestExitPin(profile){if(!profile.hasPin)return false;return new Promise((resolve)=>{const overlay=document.createElement("div");overlay.className="profile-pin";overlay.innerHTML=`<form class="profile-pin__dialog" role="dialog" aria-modal="true"><h2>Digite o PIN do perfil infantil</h2><label><span>PIN de 4 a 6 dígitos</span><input type="password" inputmode="numeric" maxlength="6" pattern="\\d{4,6}" required autocomplete="off"></label><p class="profile-pin__error" hidden>Não foi possível verificar o PIN.</p><div><button type="button" data-cancel>Cancelar</button><button type="submit">Continuar</button></div></form>`;const close=(value)=>{overlay.remove();resolve(value);};overlay.querySelector("form").addEventListener("submit",async(event)=>{event.preventDefault();const input=overlay.querySelector("input");const ok=await verifyProfilePin(profile.id,input.value);if(ok)return close(true);overlay.querySelector(".profile-pin__error").hidden=false;input.select();});overlay.querySelector("[data-cancel]").addEventListener("click",()=>close(false));document.body.appendChild(overlay);overlay.querySelector("input").focus();});}
