import { getActiveProfileRecord, initializeProfileService, listProfiles, switchActiveProfile, verifyProfilePin } from "../services/profile-service.js";

export function getProfiles(){ return listProfiles(); }
export function getActiveProfile(){ return getActiveProfileRecord(); }
export async function setActiveProfile(profileId){ const profile=await switchActiveProfile(profileId); applyProfileContext(profile); return profile; }
export function isKidsProfile(profile=getActiveProfile()){ return profile?.kind==="kids"; }
export function getContentAudience(item={}){ return item.audience || (item.kids===true ? "kids" : "general"); }
export function isKidsContentRating(value){ const rating=String(value||"").trim().toUpperCase().replace(/\s+/g,""); return ["L","LIVRE","10","10ANOS","G","PG","TV-Y","TV-Y7","TV-G","TV-PG","U","AL"].includes(rating); }
export function canAccessContent(item,profile=getActiveProfile()){ if(!isKidsProfile(profile))return true;const audience=getContentAudience(item);if(audience==="kids")return true;if(audience==="adult")return false;return isKidsContentRating(item.contentRating); }
export function filterContentByProfile(content,profile=getActiveProfile()){ return (Array.isArray(content)?content:[]).filter((item)=>canAccessContent(item,profile)); }

export async function initializeProfiles(root=document){ await initializeProfileService(); bindProfileControls(root); const active=getActiveProfile(); applyProfileContext(active); updateProfileControls(root); return active || openProfileSelector({initial:true}); }
export function bindProfileControls(root=document){ if(root.__brasaProfileControlsBound)return; root.__brasaProfileControlsBound=true; root.addEventListener("click",(event)=>{ const trigger=event.target.closest("[data-profile-switcher]"); if(trigger)openProfileSelector({trigger}); }); }
export function updateProfileControls(root=document){ const profile=getActiveProfile(); applyProfileContext(profile); root.querySelectorAll("[data-profile-switcher]").forEach((control)=>{ const name=control.querySelector("[data-profile-name]"),initials=control.querySelector("[data-profile-initials]"); control.dataset.profileId=profile?.id||""; control.setAttribute("aria-label",profile?`Trocar perfil, atual: ${profile.name}`:"Escolher perfil"); if(name)name.textContent=profile?.name||"Perfis"; if(initials)initials.textContent=profile?.initials||"?"; }); window.lucide?.createIcons?.(); }

export function openProfileSelector({initial=false,trigger=document.activeElement}={}){ const existing=document.querySelector(".profile-selector"); if(existing)return existing.__brasaProfilePromise; let resolvePromise; const promise=new Promise((resolve)=>{resolvePromise=resolve;}); const overlay=document.createElement("div"),profiles=getProfiles(),active=getActiveProfile(); overlay.__brasaProfilePromise=promise; overlay.className="profile-selector"; overlay.innerHTML=`<section class="profile-selector__dialog" role="dialog" aria-modal="true" aria-labelledby="profileSelectorTitle" aria-describedby="profileSelectorDescription"><p class="profile-selector__eyebrow">BRasa</p><h1 id="profileSelectorTitle">${initial?"Quem está assistindo?":"Trocar perfil"}</h1><p id="profileSelectorDescription">Escolha quem vai usar o BRasa agora.</p><div class="profile-selector__list">${profiles.map((p)=>`<button class="profile-selector__card ${p.id===active?.id?"is-active":""}" type="button" data-profile-id="${p.id}"><span class="profile-selector__avatar profile-avatar--${p.avatar?.color||"blue"}">${p.initials}</span><strong>${p.name}</strong><small>${p.kind==="kids"?"Perfil infantil":"Perfil adulto"}</small></button>`).join("")}</div>${isKidsProfile(active)?"":`<a class="profile-selector__manage" href="${location.pathname.includes("/pages/")?"settings.html":"pages/settings.html"}#profiles">Gerenciar perfis</a>`}${initial?"":'<button class="profile-selector__cancel" type="button" data-profile-cancel>Cancelar</button>'}</section>`;
    const dialog=overlay.querySelector("[role=dialog]"); const close=(value)=>{ overlay.remove(); trigger?.focus?.(); resolvePromise(value); };
    overlay.addEventListener("click",async(event)=>{ const button=event.target.closest("[data-profile-id]"); if(button){ const next=profiles.find((p)=>p.id===button.dataset.profileId); if(isKidsProfile(active)&&next?.kind==="adult"&&!await requestExitPin(active))return; await setActiveProfile(next.id); updateProfileControls(); close(next); location.reload(); } if(event.target.closest("[data-profile-cancel]"))close(null); });
    overlay.addEventListener("keydown",(event)=>{ if(event.key==="Escape"&&!initial)close(null); if(event.key==="Tab")trapFocus(event,dialog); }); document.body.appendChild(overlay); overlay.querySelector("[data-profile-id]")?.focus(); return promise; }

async function requestExitPin(profile){ if(!profile.hasPin)return true; return new Promise((resolve)=>{ const previous=document.activeElement,overlay=document.createElement("div"); overlay.className="profile-pin"; overlay.innerHTML=`<form class="profile-pin__dialog" role="dialog" aria-modal="true" aria-labelledby="pinTitle" aria-describedby="pinDescription"><h2 id="pinTitle">Digite o PIN parental</h2><p id="pinDescription">O PIN é necessário para sair do perfil infantil.</p><label><span>PIN de 4 dígitos</span><input type="password" inputmode="numeric" maxlength="4" pattern="\\d{4}" required autocomplete="off"></label><p class="profile-pin__error" aria-live="polite" hidden>PIN incorreto. Tente novamente.</p><div><button type="button" data-cancel>Cancelar</button><button type="submit">Continuar</button></div></form>`; const dialog=overlay.querySelector("form"),close=(value)=>{overlay.remove();previous?.focus?.();resolve(value);}; dialog.addEventListener("submit",async(event)=>{event.preventDefault();const input=dialog.querySelector("input"),ok=await verifyProfilePin(profile.id,input.value);if(ok)return close(true);const error=dialog.querySelector(".profile-pin__error");error.hidden=false;input.select();}); overlay.querySelector("[data-cancel]").onclick=()=>close(false); overlay.onkeydown=(event)=>{if(event.key==="Escape")close(false);if(event.key==="Tab")trapFocus(event,dialog);}; document.body.appendChild(overlay);dialog.querySelector("input").focus(); }); }
function applyProfileContext(profile){ const root=document.documentElement; root.dataset.profileKind=profile?.kind||""; root.dataset.profileId=profile?.id||""; }
function trapFocus(event,root){ const controls=[...root.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();} }
