import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
const CATEGORIES = new Set(["auth", "library", "sync", "media", "profiles", "collections", "settings", "error"]), LEVELS = new Set(["info", "warning", "error"]), SECRET = /password|senha|pin|hash|salt|cookie|csrf|token|api.?key/i;
export function createAdminLogService(rootDir, { limit = 2000 } = {}) { const file = path.join(rootDir, "data", "admin-logs.json"), backup = path.join(rootDir, "data", "admin-logs.backup.json"); let queue = Promise.resolve();
    async function list(filters = {}) { const state = await load(), query = String(filters.query || "").toLowerCase(), page = Math.max(1, Number(filters.page || 1)), pageSize = Math.min(100, Math.max(1, Number(filters.pageSize || 50))); const filtered = state.items.filter((item) => (!filters.category || item.category === filters.category) && (!filters.level || item.level === filters.level) && (!query || `${item.action} ${item.message}`.toLowerCase().includes(query))); return { items: filtered.slice((page - 1) * pageSize, page * pageSize), total: filtered.length, page, pageSize }; }
    async function add(input) { const entry = { id: crypto.randomBytes(10).toString("hex"), timestamp: new Date().toISOString(), category: CATEGORIES.has(input.category) ? input.category : "error", level: LEVELS.has(input.level) ? input.level : "info", action: String(input.action || "event").slice(0, 80), message: String(input.message || "").slice(0, 500), details: scrub(input.details || {}) }; await update((state) => ({ version: 1, items: [entry, ...state.items].slice(0, limit) })); return entry; }
    async function clear() { await update(() => ({ version: 1, items: [] })); return true; }
    async function load() { const text = await fs.readFile(file, "utf8").catch(() => ""); if (!text) return { version: 1, items: [] }; try { const value = JSON.parse(text); return { version: 1, items: Array.isArray(value.items) ? value.items : [] }; } catch { await fs.rename(file, `${file}.corrupt-${Date.now()}`).catch(() => {}); return fs.readFile(backup, "utf8").then(JSON.parse).catch(() => ({ version: 1, items: [] })); } }
    function update(mutator) { queue = queue.then(async () => { const state = mutator(await load()), temp = `${file}.${process.pid}.tmp`, old = await fs.readFile(file, "utf8").catch(() => ""); await fs.mkdir(path.dirname(file), { recursive: true }); if (old) await fs.writeFile(backup, old); await fs.writeFile(temp, `${JSON.stringify(state, null, 2)}\n`); await fs.rename(temp, file); }); return queue; }
    return { list, add, clear };
}
export function scrub(value) { if (Array.isArray(value)) return value.map(scrub); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value).filter(([key]) => !SECRET.test(key)).map(([key, item]) => [key, scrub(item)])); }
