import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { ConflictError, UnauthorizedError, ValidationError, ForbiddenError } from "./app-errors.mjs";

const IDLE_MS = 30 * 60 * 1000, MAX_MS = 8 * 60 * 60 * 1000;
export function createAdminAuthService({ rootDir, now = () => Date.now(), randomBytes = crypto.randomBytes, scrypt = crypto.scrypt }) {
    const file = path.join(rootDir, ".brasa-admin.json"), sessions = new Map(), attempts = new Map(); let writeQueue = Promise.resolve();
    const derive = (password, salt) => new Promise((resolve, reject) => scrypt(password, salt, 64, (error, key) => error ? reject(error) : resolve(Buffer.from(key))));
    async function configured() { return Boolean((await readConfig())?.passwordHash); }
    async function setup(password, confirmation) { if (await configured()) throw new ConflictError("O administrador já está configurado."); validatePassword(password, confirmation); const createdAt = new Date(now()).toISOString(), salt = randomBytes(24).toString("hex"), key = await derive(password, salt); await writeConfig({ version: 1, algorithm: "scrypt", salt, passwordHash: key.toString("hex"), keyLength: 64, createdAt, updatedAt: createdAt }); return createSession(); }
    async function login(password, identity = "local") { const config = await readConfig(); if (!config?.passwordHash) throw new ConflictError("Configure a senha administrativa primeiro."); const record = attempts.get(identity) || { count: 0, level: 0, blockedUntil: 0 }; if (now() < record.blockedUntil) throw new ForbiddenError("Muitas tentativas. Aguarde antes de tentar novamente."); const actual = await derive(String(password || ""), config.salt), expected = Buffer.from(config.passwordHash, "hex"), valid = actual.length === expected.length && crypto.timingSafeEqual(actual, expected); if (!valid) { record.count++; if (record.count >= 5) { record.level++; record.count = 0; record.blockedUntil = now() + Math.min(5 * 60_000, 30_000 * record.level); } attempts.set(identity, record); throw new UnauthorizedError("Credenciais inválidas."); } attempts.delete(identity); return createSession(); }
    function createSession() { const token = randomBytes(32).toString("base64url"), csrf = randomBytes(24).toString("base64url"), createdAt = now(); sessions.set(token, { token, csrf, createdAt, lastActivityAt: createdAt, expiresAt: createdAt + MAX_MS }); return { token, csrf, cookie: sessionCookie(token, MAX_MS) }; }
    function requireSession(request, { csrf = false } = {}) { const token = parseCookies(request.headers?.cookie || "").brasa_admin_session, session = token ? sessions.get(token) : null, time = now(); if (!session || time - session.lastActivityAt > IDLE_MS || time >= session.expiresAt) { if (token) sessions.delete(token); throw new UnauthorizedError("Sessão administrativa ausente ou expirada."); } if (csrf && String(request.headers?.["x-brasa-csrf"] || "") !== session.csrf) throw new ForbiddenError("Token CSRF inválido."); session.lastActivityAt = time; return { authenticated: true, csrf: session.csrf, createdAt: session.createdAt, expiresAt: session.expiresAt }; }
    function logout(request) { const token = parseCookies(request.headers?.cookie || "").brasa_admin_session; if (token) sessions.delete(token); return { cookie: expiredCookie() }; }
    async function changePassword(request, currentPassword, password, confirmation) { requireSession(request, { csrf: true }); const config = await readConfig(); const actual = await derive(String(currentPassword || ""), config.salt), expected = Buffer.from(config.passwordHash, "hex"); if (actual.length !== expected.length || !crypto.timingSafeEqual(actual, expected)) throw new UnauthorizedError("Senha atual inválida."); validatePassword(password, confirmation); const salt = randomBytes(24).toString("hex"), key = await derive(password, salt); await writeConfig({ ...config, salt, passwordHash: key.toString("hex"), keyLength: 64, updatedAt: new Date(now()).toISOString() }); sessions.clear(); return { cookie: expiredCookie() }; }
    async function status(request) { let authenticated = false; try { requireSession(request); authenticated = true; } catch {} return { configured: await configured(), authenticated }; }
    async function readConfig() { const text = await fs.readFile(file, "utf8").catch((error) => error.code === "ENOENT" ? "" : Promise.reject(error)); if (!text) return null; try { return JSON.parse(text); } catch (error) { await fs.rename(file, `${file}.corrupt-${now()}`).catch(() => {}); throw new ValidationError("A configuração administrativa está corrompida.", error.message); } }
    function writeConfig(value) { writeQueue = writeQueue.then(async () => { const temp = `${file}.${process.pid}.tmp`; await fs.writeFile(temp, `${JSON.stringify(value, null, 2)}\n`, { encoding: "utf8", mode: 0o600 }); await fs.rename(temp, file); }); return writeQueue; }
    return { configured, setup, login, logout, changePassword, status, requireSession, sessionCount: () => sessions.size };
}
export function validatePassword(password, confirmation = password) { const value = String(password || ""); if (value !== String(confirmation || "")) throw new ValidationError("A confirmação da senha não confere."); if (value.length < 8 || !/[A-Za-zÀ-ÿ]/.test(value) || !/\d/.test(value) || !value.trim()) throw new ValidationError("Use pelo menos 8 caracteres, uma letra e um número."); return true; }
function parseCookies(value) { return Object.fromEntries(String(value).split(";").map((part) => part.trim().split("=")).filter(([key]) => key).map(([key, item]) => [key, decodeURIComponent(item || "")])); }
function sessionCookie(token, maxAge) { return `brasa_admin_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${Math.floor(maxAge / 1000)}`; }
function expiredCookie() { return "brasa_admin_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0"; }
