import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { buildLibraryIssues, mergeIssueHistory } from "./library-audit.mjs";
import { absoluteLibraryRoots, VIDEO_EXTENSIONS } from "./library-config.mjs";

const videoExtensions = new Set(VIDEO_EXTENSIONS);
export function createLibraryHealth({ rootDir, store, mediaStore, mediaQueue, syncHistory }) {
    let running = null, cancelled = false;
    async function audit(type = "quick") { if (running) throw new Error("Já existe uma verificação em andamento."); const operation = { id: `audit-${Date.now().toString(36)}`, type, status: "running", progress: 0, startedAt: new Date().toISOString() }; cancelled = false; running = operation; await store.update({ activeAudit: operation }); execute(operation).catch((error) => console.error("BRasa auditoria:", error)); return operation; }
    async function execute(operation) { try { const snapshot = await collectSnapshot(operation.type === "full"); if (cancelled) throw new Error("cancelled"); operation.progress = 70; await store.update({ activeAudit: operation }); const detected = buildLibraryIssues({ ...snapshot, full: operation.type === "full" }); const previous = (await store.load()).issues, issues = mergeIssueHistory(previous, detected), open = issues.filter((item) => item.status === "open"), errors = open.filter((item) => ["error", "critical"].includes(item.severity)).length, warnings = open.filter((item) => item.severity === "warning").length; const summary = { totalItems: snapshot.items.length, healthyItems: Math.max(0, snapshot.items.length - new Set(open.map((item) => item.mediaKey).filter(Boolean)).size), issues: open.length, warnings, errors, critical: open.filter((item) => item.severity === "critical").length, orphans: open.filter((item) => item.type === "orphan-file").length, duplicates: open.filter((item) => item.type.includes("duplicate")).length, missingFiles: open.filter((item) => item.type === "missing-file").length, processing: Object.values(snapshot.mediaItems).filter((item) => ["queued", "analyzing", "processing"].includes(item.status)).length }; operation.status = "complete"; operation.progress = 100; operation.completedAt = new Date().toISOString(); const state = await store.load(); await store.update({ lastAuditAt: operation.completedAt, summary, issues, auditHistory: [operation, ...state.auditHistory].slice(0, 50), activeAudit: null, storage: snapshot.storage }); } catch (error) { operation.status = error.message === "cancelled" ? "cancelled" : "failed"; operation.error = error.message === "cancelled" ? "Verificação cancelada." : error.message; operation.completedAt = new Date().toISOString(); const state = await store.load(); await store.update({ activeAudit: null, auditHistory: [operation, ...state.auditHistory].slice(0, 50) }); } finally { running = null; } }
    async function collectSnapshot(full) { const [moviesModule, seriesModule, media] = await Promise.all([loadData("movies.js"), loadData("series.js"), mediaStore.all()]), items = []; for (const movie of moviesModule.getMovies()) items.push(await hydrate({ mediaKey: `movie:${movie.id}`, mediaType: "movie", mediaId: movie.id, ...movie }, media.items)); for (const series of seriesModule.getSeries()) for (const season of series.seasons || []) for (const episode of season.episodes || []) items.push(await hydrate({ mediaKey: `episode:${episode.id}`, mediaType: "episode", mediaId: episode.id, title: `${series.title} — ${episode.title || `Episódio ${episode.episodeNumber || ""}`}`, poster: series.poster, overview: episode.title, year: series.year, contentRating: series.contentRating, thumbnail: episode.thumbnail, episodeNumber: episode.episodeNumber, seasonNumber: season.seasonNumber, video: episode.video, subtitles: episode.subtitles || [], imdbId: series.imdbId, tmdbId: series.tmdbId }, media.items)); let files = [], tempFiles = []; if (full) { for (const root of absoluteLibraryRoots(rootDir)) for (const file of await walk(root.absolutePath)) { const relativePath = rel(file.path); if (videoExtensions.has(path.extname(file.path).toLowerCase()) && file.stat.size > 0) files.push({ name: path.basename(file.path), relativePath, mediaType: root.type === "movie" ? "movie" : "episode", audience: root.audience, size: file.stat.size }); if (/\.(?:part|tmp|partial)$/i.test(file.path) && Date.now() - file.stat.mtimeMs > 3600000) tempFiles.push({ name: path.basename(file.path), relativePath }); } for (const file of await walk(path.join(rootDir, "data", "prepared-media"))) if (file.path.endsWith(".part") && Date.now() - file.stat.mtimeMs > 3600000) tempFiles.push({ name: path.basename(file.path), relativePath: rel(file.path) }); } return { items, files, tempFiles, mediaItems: media.items, storage: await storage() }; }
    async function hydrate(item, mediaItems) { const media = mediaItems[item.mediaKey]; if (media?.originalPath) item.video = media.originalPath; item.fileExists = item.video ? await exists(path.resolve(rootDir, item.video)) : false; item.subtitles = await Promise.all((item.subtitles || []).map(async (subtitle) => ({ ...subtitle, fileExists: await exists(path.resolve(rootDir, subtitle.src || "")) }))); if (media?.preparedPath) { media.preparedExists = await exists(path.resolve(rootDir, media.preparedPath)); if (media.preparedExists && item.fileExists) { const [original, prepared] = await Promise.all([fs.stat(path.resolve(rootDir, item.video)), fs.stat(path.resolve(rootDir, media.preparedPath))]); media.preparedOutdated = prepared.mtimeMs < original.mtimeMs; } } return item; }
    async function storage() { const groups = { originals: 0, prepared: 0, thumbnails: 0, backdrops: 0, subtitles: 0, temp: 0, state: 0 }; const folders = [...absoluteLibraryRoots(rootDir).map((root) => [root.relativePath, "originals"]), ["data/prepared-media/movies", "prepared"], ["data/prepared-media/episodes", "prepared"], ["data/prepared-media/thumbnails", "thumbnails"], ["data/prepared-media/backdrops", "backdrops"], ["data/prepared-media/subtitles", "subtitles"]]; for (const [folder, key] of folders) for (const file of await walk(path.join(rootDir, folder))) groups[file.path.endsWith(".part") ? "temp" : key] += file.stat.size; for (const file of ["data/media-state.json", "data/user-state.json", "data/library-health.json"]) groups.state += (await fs.stat(path.join(rootDir, file)).catch(() => ({ size: 0 }))).size; let free = 0; if (fs.statfs) { const stats = await fs.statfs(rootDir); free = Number(stats.bavail) * Number(stats.bsize); } return { ...groups, totalPrepared: groups.prepared + groups.thumbnails + groups.backdrops + groups.subtitles, free }; }
    async function health() { return store.load(); } async function issues() { return (await store.load()).issues; }
    async function setIssue(id, action) { const now = new Date().toISOString(); if (action === "ignore") return store.updateIssue(id, { status: "ignored", ignoredAt: now }); if (action === "restore") return store.updateIssue(id, { status: "open", ignoredAt: null, resolvedAt: null }); return store.updateIssue(id, { status: "resolved", resolvedAt: now }); }
    async function retry(id) { const issue = await store.issue(id); if (!issue) throw new Error("Problema não encontrado."); if (["retry-media", "prepare-media", "reanalyze"].includes(issue.suggestedAction)) return issue.suggestedAction === "reanalyze" ? mediaQueue.analyze(issue.mediaKey, { priority: 30 }) : mediaQueue.retry(issue.mediaKey); throw new Error("Este problema precisa de revisão manual."); }
    function cancel() { if (!running) return false; cancelled = true; return true; } function status() { return running; }
    async function loadData(name) { return import(`${pathToFileURL(path.join(rootDir, "data", name)).href}?t=${Date.now()}`); }
    async function walk(dir) { const output = []; for (const entry of await fs.readdir(dir, { withFileTypes: true }).catch(() => [])) { if (cancelled) break; const file = path.join(dir, entry.name); if (entry.isDirectory()) output.push(...await walk(file)); else { const stat = await fs.stat(file).catch(() => null); if (stat) output.push({ path: file, stat }); } } return output; }
    const exists = (file) => fs.access(file).then(() => true).catch(() => false); const rel = (file) => path.relative(rootDir, file).replace(/\\/g, "/");
    return { audit, cancel, status, health, issues, setIssue, retry, storage, syncHistory };
}
