import fs from "node:fs/promises";import path from "node:path";import {spawn} from "node:child_process";import {probeMedia} from "./media-probe.mjs";import {decideMediaStrategy,isProbeStillValid} from "./media-compatibility.mjs";import {resolvePathInsideLibrary} from "./library-config.mjs";
export function createMediaQueue({rootDir,store,getTools,resolveMedia}){const pending=[],active=new Map();let paused=false;const safeKey=(key)=>String(key).replace(/[^a-zA-Z0-9._-]/g,"-");async function analyze(key,{prepare=false,priority=0}={}){if(active.has(key)||pending.some((j)=>j.key===key))throw new Error("Este item já está na fila.");const media=await resolveMedia(key);if(!media)throw new Error("Mídia não encontrada.");const original=resolveOriginal(media.originalPath);const tools=await getTools();if(!tools.ffprobeAvailable)throw new Error("FFprobe não está disponível.");await store.update(key,{mediaKey:key,mediaType:media.mediaType,mediaId:String(media.mediaId),originalPath:media.originalPath,preparedPath:"",status:"queued",strategy:"pending",progress:0,error:"",createdAt:new Date().toISOString()});pending.push({key,original,media,prepare,priority,kind:"analyze"});pending.sort((a,b)=>b.priority-a.priority);schedule();return store.get(key);}
async function prepare(key,{priority=10}={}){if(active.has(key)||pending.some((j)=>j.key===key))throw new Error("Este item já está na fila.");const item=await store.get(key),media=await resolveMedia(key);if(!media)throw new Error("Mídia não encontrada.");pending.push({key,original:resolveOriginal(media.originalPath),media,priority,kind:item?.probe?"prepare":"analyze",prepare:true});pending.sort((a,b)=>b.priority-a.priority);await store.update(key,{status:"queued",progress:0,error:""});schedule();return store.get(key);}
function schedule(){if(paused||active.size)return;const job=pending.shift();if(!job)return;run(job).finally(()=>{active.delete(job.key);schedule();});}
async function run(job){active.set(job.key,{job,child:null});try{let item=await store.get(job.key),probe=item?.probe;const stat=await fs.stat(job.original);if(!probe||!isProbeStillValid(item,stat)){await store.update(job.key,{status:"analyzing",progress:0});const tools=await getTools();probe=await probeMedia(job.original,tools.ffprobePath);const settings={...(await store.settings()),hardwareAcceleration:tools.hardwareAcceleration};const decision=decideMediaStrategy(probe,settings);item=await store.update(job.key,{probe,fingerprint:probe.fingerprint,strategy:decision.strategy,reason:decision.reason,decision,status:decision.strategy==="direct-play"?"ready":decision.strategy==="corrupted"?"corrupted":"pending",progress:decision.strategy==="direct-play"?100:0,lastAnalyzedAt:new Date().toISOString()});if(item.status==="ready"||!job.prepare)return;}if(job.prepare)await process(job.key,job.original,probe,item.decision||decideMediaStrategy(probe,await store.settings()));}catch(error){const cancelled=error.message==="cancelled";await store.update(job.key,{status:cancelled?"cancelled":"failed",error:cancelled?"Processamento cancelado.":error.message.slice(0,500)});}}
async function process(key,original,probe,decision){if(["unsupported","corrupted"].includes(decision.strategy))throw new Error("Este arquivo não pode ser preparado automaticamente.");const tools=await getTools();if(!tools.ffmpegAvailable)throw new Error("FFmpeg não está disponível.");const settings=await store.settings();await ensureSpace(original,settings);const type=key.startsWith("episode:")?"episodes":"movies",dir=path.join(rootDir,"data","prepared-media",type);await fs.mkdir(dir,{recursive:true});const output=path.join(dir,`${safeKey(key)}.browser.mp4`),part=`${output}.part`;await fs.rm(part,{force:true});const args=buildArgs(original,part,decision,settings);await store.update(key,{status:"processing",progress:0,preparedPath:relative(output),startedAt:new Date().toISOString()});try{await runFfmpeg(key,tools.ffmpegPath,args,probe.duration);}catch(error){await fs.rm(part,{force:true});if(settings.cpuFallback&&["h264_nvenc","h264_qsv","h264_amf"].includes(decision.videoAction)){await store.update(key,{error:"A aceleração por hardware falhou; tentando pela CPU."});await runFfmpeg(key,tools.ffmpegPath,buildArgs(original,part,{...decision,videoAction:"libx264"},settings),probe.duration);}else throw error;}await fs.rename(part,output);const stat=await fs.stat(output);await generateAssets(key,original,probe,tools.ffmpegPath);await store.update(key,{status:"ready",progress:100,preparedPath:relative(output),output:{container:"mp4",videoCodec:decision.videoAction==="copy"?probe.video.codec:"h264",audioCodec:decision.audioAction==="copy"?probe.audioTracks[0]?.codec||"":"aac",size:stat.size},completedAt:new Date().toISOString(),error:""});}
function buildMediaPreparationArgs(input, output, decision, settings) {
    const nvenc = decision.videoAction === "h264_nvenc" && decision.strategy === "video-transcode";
    const args = ["-y", ...(nvenc ? ["-hwaccel", "cuda", "-hwaccel_output_format", "cuda"] : []), "-i", input, "-map", "0:v:0", "-map", "0:a:0?", "-map_metadata", "0"];
    if (decision.strategy === "remux") args.push("-c", "copy");
    else if (decision.strategy === "audio-transcode") args.push("-c:v", "copy", "-c:a", "aac", "-b:a", "256k");
    else {
        const quality = { economy: 26, balanced: 22, high: 18 }[settings.quality] || 22;
        if (nvenc) args.push("-vf", "scale_cuda=passthrough=0:format=yuv420p");
        args.push("-c:v", decision.videoAction || "libx264");
        if (decision.videoAction === "libx264") args.push("-preset", "medium", "-crf", String(quality), "-pix_fmt", "yuv420p");
        else if (nvenc) args.push("-preset", "p1", "-tune", "ll", "-rc", "vbr", "-cq", String(Math.max(quality, 24)), "-spatial-aq", "1");
        else args.push("-cq", String(quality), "-pix_fmt", "yuv420p");
        args.push("-c:a", "aac", "-b:a", "256k");
    }
    return [...args, "-movflags", "+faststart", "-progress", "pipe:1", "-nostats", "-f", "mp4", output];
}
const buildArgs=buildMediaPreparationArgs;
function runFfmpeg(key,command,args,duration){return new Promise((resolve,reject)=>{const child=spawn(command,args,{windowsHide:true,shell:false}),entry=active.get(key);entry.child=child;let buffer="",lastSave=0,lastError="";child.stdout.on("data",async(chunk)=>{buffer+=chunk;const lines=buffer.split(/\r?\n/);buffer=lines.pop()||"";for(const line of lines){const [name,value]=line.split("=");if(name==="out_time_ms"){const percent=Math.min(99,Math.max(0,Number(value)/1e6/duration*100));if(Date.now()-lastSave>2000){lastSave=Date.now();store.update(key,{progress:Number(percent.toFixed(1))}).catch(()=>{});}}}});child.stderr.on("data",(c)=>lastError=(lastError+c).slice(-4000));child.on("error",reject);child.on("close",(code)=>{if(entry.cancelled)return reject(new Error("cancelled"));code===0?resolve():reject(new Error(lastError.slice(-800)||`FFmpeg terminou com código ${code}.`));});});}
async function generateAssets(key,input,probe,ffmpeg){const settings=await store.settings(),base=safeKey(key),seek=String(Math.max(10,probe.duration*.2)),generated={subtitles:[]};if(settings.generateThumbnails){const kind=key.startsWith("episode:")?"thumbnails":"backdrops",dir=path.join(rootDir,"data","prepared-media",kind),output=path.join(dir,`${base}.jpg`);await fs.mkdir(dir,{recursive:true});const size=key.startsWith("episode:")?"640:360":"1280:720";if(await spawnAndWait(ffmpeg,["-y","-ss",seek,"-i",input,"-frames:v","1","-vf",`scale=${size}:force_original_aspect_ratio=decrease,pad=${size}:(ow-iw)/2:(oh-ih)/2`,output]).then(()=>true).catch(()=>false))generated[kind==="thumbnails"?"thumbnail":"backdrop"]=relative(output);}if(settings.extractSubtitles){const tracks=probe.subtitleTracks.filter((s)=>s.extractable).slice(0,4),dir=path.join(rootDir,"data","prepared-media","subtitles");await fs.mkdir(dir,{recursive:true});for(const track of tracks){const output=path.join(dir,`${base}-${track.language}-${track.index}.vtt`);if(await spawnAndWait(ffmpeg,["-y","-i",input,"-map",`0:${track.index}`,output]).then(()=>true).catch(()=>false))generated.subtitles.push({label:track.title||track.language,srclang:normalizeLanguage(track.language),src:relative(output),default:track.default,source:"embedded"});}}await store.update(key,generated);}
function normalizeLanguage(value){return ({por:"pt-br",pt:"pt-br",eng:"en",spa:"es"})[String(value).toLowerCase()]||String(value||"und").toLowerCase();}
function cancel(key){const entry=active.get(key);if(entry){entry.cancelled=true;entry.child?.kill("SIGKILL");return true;}const index=pending.findIndex((j)=>j.key===key);if(index>=0){pending.splice(index,1);store.update(key,{status:"cancelled"});return true;}return false;}
async function removePrepared(key){if(active.has(key))throw new Error("Cancele o processamento antes de remover.");const item=await store.get(key);if(item?.preparedPath){const file=path.resolve(rootDir,item.preparedPath);if(!insidePrepared(file))throw new Error("Caminho preparado inválido.");await fs.rm(file,{force:true});}return store.update(key,{preparedPath:"",status:item?.strategy==="direct-play"?"ready":"pending",progress:0,output:null});}
function resolveOriginal(relativePath){return resolvePathInsideLibrary(rootDir,relativePath).path;}function insidePrepared(file){return file.startsWith(path.join(rootDir,"data","prepared-media")+path.sep);}function relative(file){return path.relative(rootDir,file).replace(/\\/g,"/");}
async function ensureSpace(file,settings){if(!fs.statfs)return;const stat=await fs.statfs(path.dirname(file));const free=Number(stat.bavail)*Number(stat.bsize);if(free<Number(settings.minimumFreeGb||5)*1024**3)throw new Error("Espaço livre insuficiente para preparar a mídia.");}
function spawnAndWait(command,args){return new Promise((resolve,reject)=>{const p=spawn(command,args,{windowsHide:true,shell:false,stdio:"ignore"});p.on("error",reject);p.on("close",(code)=>code===0?resolve():reject(new Error("Processo auxiliar falhou.")));});}
async function restore(){const state=await store.all(),settings=await store.settings(),tools=await getTools();paused=Boolean(settings.paused);if(!tools.ffprobeAvailable){for(const item of Object.values(state.items||{}))if(/ffprobe/i.test(item.error||"")||["queued","analyzing"].includes(item.status))await store.update(item.mediaKey,{status:"not-analyzed",error:"",progress:0});return;}for(const item of Object.values(state.items||{})){if(["queued","analyzing","processing","finalizing"].includes(item.status))prepare(item.mediaKey,{priority:5}).catch((error)=>console.error(`BRasa mídia ${item.mediaKey} restore tentativa 1 ${new Date().toISOString()}:`,error.message));}}
return {analyze,prepare,cancel,retry:(key)=>prepare(key,{priority:20}),removePrepared,restore,pause:()=>{paused=true;store.setSettings({paused:true});},resume:()=>{paused=false;store.setSettings({paused:false});schedule();},snapshot:()=>({paused,queued:pending.map((j)=>({mediaKey:j.key,type:j.kind})),active:[...active.keys()]})};}
