import crypto from "node:crypto";
import { ConflictError, ForbiddenError, NotFoundError } from "./app-errors.mjs";

export function createPairingService({ deviceStore, getSettings, now = () => Date.now(), randomBytes = crypto.randomBytes, ttlMs = 5 * 60_000 } = {}) {
    const requests = new Map(), attempts = new Map();
    function cleanup() { for (const [id, item] of requests) { if (now() >= item.expiresAt && item.status === "pending") { item.status = "expired"; item.token = ""; } if (now() >= item.expiresAt + 10 * 60_000) requests.delete(id); } for (const [ip, record] of attempts) if (now() - record.startedAt > 10 * 60_000) attempts.delete(ip); }
    async function start({ name, type, ip }) { cleanup(); const settings = await getSettings(); if (!settings.lanAccessEnabled || !settings.allowNewDevices) throw new ForbiddenError("Novos dispositivos não estão disponíveis."); const identity = String(ip || "unknown"), record = attempts.get(identity) || { count: 0, startedAt: now() }; if (now() - record.startedAt > 10 * 60_000) { record.count = 0; record.startedAt = now(); } if (++record.count > 5) { attempts.set(identity, record); throw new ForbiddenError("Muitas solicitações de pareamento. Aguarde alguns minutos."); } attempts.set(identity, record); const id = randomBytes(18).toString("base64url"), code = createCode(randomBytes), createdAt = now(); requests.set(id, { id, code, name: String(name || "TV BRasa").slice(0, 80), type: String(type || "tv").slice(0, 20), ip: identity.slice(0, 64), status: "pending", createdAt, expiresAt: createdAt + ttlMs, token: "", device: null, delivered: false }); return publicRequest(requests.get(id), true, now()); }
    function status(id) { cleanup(); const item = requests.get(id); if (!item) throw new NotFoundError("Solicitação de pareamento não encontrada."); const result = publicRequest(item, false, now()); if (item.status === "approved" && item.token && !item.delivered) { result.token = item.token; result.device = item.device; item.delivered = true; item.token = ""; } return result; }
    async function approve(id, allowedProfileIds = []) { cleanup(); const item = requests.get(id); if (!item) throw new NotFoundError("Pareamento não encontrado."); if (item.status !== "pending" || now() >= item.expiresAt) throw new ConflictError("Este pareamento não está mais pendente."); const settings = await getSettings(), result = await deviceStore.create({ name: item.name, type: item.type, allowedProfileIds, maxDevices: settings.maxAuthorizedDevices, ip: item.ip }); item.status = "approved"; item.token = result.token; item.device = result.device; return publicRequest(item, false, now()); }
    function reject(id) { cleanup(); const item = requests.get(id); if (!item) throw new NotFoundError("Pareamento não encontrado."); if (item.status !== "pending") throw new ConflictError("Este pareamento não está mais pendente."); item.status = "rejected"; item.token = ""; return publicRequest(item, false, now()); }
    function list() { cleanup(); return [...requests.values()].filter((item) => item.status === "pending").map((item) => publicRequest(item, false, now())); }
    return { start, status, approve, reject, list, cleanup };
}
function createCode(randomBytes) { const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789", bytes = randomBytes(6); return [...bytes].map((value) => alphabet[value % alphabet.length]).join(""); }
function publicRequest(item, includeCode, currentTime) { return { requestId: item.id, ...(includeCode ? { code: item.code } : {}), name: item.name, type: item.type, ip: item.ip, status: item.status, createdAt: new Date(item.createdAt).toISOString(), expiresAt: new Date(item.expiresAt).toISOString(), remainingMs: Math.max(0, item.expiresAt - currentTime) }; }
