package com.brasa.tv.feature.update
import kotlinx.coroutines.runBlocking
import org.junit.Assert.*
import org.junit.Test
import java.nio.file.Files
import java.security.MessageDigest
class ApkValidatorTest{private val certificate="C".repeat(64);private fun manifest(bytes:ByteArray)=UpdateManifest(packageName="com.brasa.tv",versionCode=2,versionName="1.0.1",sizeBytes=bytes.size.toLong(),sha256=MessageDigest.getInstance("SHA-256").digest(bytes).joinToString(""){"%02X".format(it)},signingCertificateSha256=certificate)
@Test fun acceptsMatchingPackageVersionHashSizeAndCertificate()=runBlocking{val bytes="valid-apk".encodeToByteArray();val file=Files.createTempFile("brasa",".apk").toFile().apply{writeBytes(bytes)};val inspector=fake(ApkIdentity("com.brasa.tv",2,certificate),certificate);try{assertTrue(ApkValidator(inspector,1,certificate).validate(file,manifest(bytes)).valid)}finally{file.delete()}}
@Test fun blocksHashPackageDowngradeCertificateAndSize()=runBlocking{val bytes="apk".encodeToByteArray();val file=Files.createTempFile("brasa",".apk").toFile().apply{writeBytes(bytes)};val valid=manifest(bytes);try{assertEquals(ApkValidationError.HASH,ApkValidator(fake(ApkIdentity("com.brasa.tv",2,certificate),certificate),1,certificate).validate(file,valid.copy(sha256="A".repeat(64))).error);assertEquals(ApkValidationError.PACKAGE,ApkValidator(fake(ApkIdentity("outro",2,certificate),certificate),1,certificate).validate(file,valid).error);assertEquals(ApkValidationError.VERSION,ApkValidator(fake(ApkIdentity("com.brasa.tv",1,certificate),certificate),1,certificate).validate(file,valid.copy(versionCode=1)).error);assertEquals(ApkValidationError.CERTIFICATE,ApkValidator(fake(ApkIdentity("com.brasa.tv",2,"D".repeat(64)),certificate),1,certificate).validate(file,valid).error);assertEquals(ApkValidationError.SIZE,ApkValidator(fake(ApkIdentity("com.brasa.tv",2,certificate),certificate),1,certificate).validate(file,valid.copy(sizeBytes=99)).error)}finally{file.delete()}}
private fun fake(identity:ApkIdentity?,installed:String)=object:ApkInspector{override fun inspect(file:java.io.File)=identity;override fun installedCertificate(packageName:String)=installed}}
