$NodeFromCodex = Join-Path $env:USERPROFILE ".cache\codex-runtimes\codex-primary-runtime\dependencies\node\bin\node.exe"
$Node = "node"

if (Test-Path -LiteralPath $NodeFromCodex) {
    $Node = $NodeFromCodex
}

& $Node (Join-Path $PSScriptRoot "sync-movies.mjs") @args
$NodeExitCode = $LASTEXITCODE

function Get-BrasaEnvValue {
    param([string]$Name)

    $envPath = Join-Path (Split-Path $PSScriptRoot -Parent) ".env"
    if (!(Test-Path -LiteralPath $envPath)) {
        return ""
    }

    foreach ($line in Get-Content -LiteralPath $envPath) {
        $trimmed = $line.Trim()
        if (!$trimmed -or $trimmed.StartsWith("#")) {
            continue
        }

        $parts = $trimmed.Split("=", 2)
        if ($parts.Length -eq 2 -and $parts[0] -eq $Name) {
            return $parts[1].Trim()
        }
    }

    return ""
}

function Resolve-VideoTool {
    param(
        [string]$ConfiguredPath,
        [string]$CommandName
    )

    if ($ConfiguredPath -and (Test-Path -LiteralPath $ConfiguredPath)) {
        return $ConfiguredPath
    }

    $command = Get-Command $CommandName -ErrorAction SilentlyContinue
    if ($command) {
        return $command.Source
    }

    return ""
}

function Format-VideoTimestamp {
    param([double]$Seconds)

    $rounded = [Math]::Max(0, [Math]::Floor($Seconds))
    $span = [TimeSpan]::FromSeconds($rounded)
    return "{0:00}:{1:00}:{2:00}" -f [Math]::Floor($span.TotalHours), $span.Minutes, $span.Seconds
}

function Get-Slug {
    param([string]$Value)

    $normalized = $Value.Normalize([Text.NormalizationForm]::FormD)
    $withoutMarks = [Text.RegularExpressions.Regex]::Replace($normalized, "\p{Mn}", "")
    $slug = $withoutMarks.ToLowerInvariant() -replace "[^a-z0-9]+", "-"
    return $slug.Trim("-")
}

function Write-SeriesData {
    param($Series)

    $root = Split-Path $PSScriptRoot -Parent
    $dataPath = Join-Path $root "data\series.js"
    $json = $Series | ConvertTo-Json -Depth 100
    $content = @"
// ==========================================================
// BRasa
// Series Repository
// Generated by scripts/sync-movies.mjs
// ==========================================================

const seriesData = $json;

function toArray(value){
    if (Array.isArray(value)) return value;
    return value ? [value] : [];
}

const series = toArray(seriesData).map((item) => ({
    ...item,
    seasons: toArray(item.seasons).map((season) => ({
        ...season,
        episodes: toArray(season.episodes)
    }))
}));

export function getSeries(){
    return series;
}

export function getRecentlyAddedSeries(limit = 12){
    return [...series]
        .sort((a, b) => new Date(b.addedAt) - new Date(a.addedAt))
        .slice(0, limit);
}

export function getSeriesById(id){
    return series.find((item) => String(item.id) === String(id));
}

export function getEpisodeById(id){
    for (const item of series) {
        for (const season of item.seasons || []) {
            const episode = (season.episodes || []).find((candidate) => String(candidate.id) === String(id));

            if (episode) {
                return {
                    ...episode,
                    seriesId: item.id,
                    seriesTitle: item.title,
                    series
                };
            }
        }
    }

    return null;
}
"@

    Set-Content -LiteralPath $dataPath -Value $content -Encoding UTF8
}

function Write-MoviesData {
    param($Movies)

    $root = Split-Path $PSScriptRoot -Parent
    $dataPath = Join-Path $root "data\movies.js"
    $json = @($Movies) | ConvertTo-Json -Depth 100
    $content = @"
// ==========================================================
// BRasa
// Movies Repository
// Generated by scripts/sync-movies.mjs
// ==========================================================

const movies = $json;

/* ==========================================================
   GETTERS
========================================================== */

export function getMovies(){

    return movies;

}

export function getFeaturedMovie(){

    return movies.find(

        movie => movie.featured

    );

}

export function getRecentlyAddedMovies(limit = 4){

    return [...movies]
        .sort((a, b) => {
            const dateA = a.addedAt ? new Date(a.addedAt).getTime() : 0;
            const dateB = b.addedAt ? new Date(b.addedAt).getTime() : 0;

            return (dateB - dateA) || (Number(b.id || 0) - Number(a.id || 0));
        })
        .slice(0, limit);

}

export function getFavorites(){

    return movies.filter(

        movie => movie.favorite

    );

}

export function getContinueWatching(){

    return movies.filter(

        movie => movie.progress > 0

    );

}

export function getAvailableMovies(){

    return movies.filter(

        movie => movie.video

    );

}

export function getMovieById(id){

    return movies.find(

        movie => movie.id === id

    );

}
"@

    Set-Content -LiteralPath $dataPath -Value $content -Encoding UTF8
}

function Set-BrasaProperty {
    param(
        $Object,
        [string]$Name,
        $Value
    )

    $previous = if ($Object.PSObject.Properties.Name -contains $Name) { $Object.$Name } else { $null }

    if ($Object.PSObject.Properties.Name -contains $Name) {
        $Object.$Name = $Value
    } else {
        $Object | Add-Member -NotePropertyName $Name -NotePropertyValue $Value
    }

    return $previous -ne $Value
}

function Get-VideoDuration {
    param(
        [string]$Ffprobe,
        [string]$InputPath
    )

    if (!$Ffprobe) {
        return 0
    }

    $duration = 0
    $probeOutput = & $Ffprobe -v error -show_entries format=duration -of "default=noprint_wrappers=1:nokey=1" $InputPath 2>$null
    [double]::TryParse(($probeOutput | Select-Object -First 1), [Globalization.NumberStyles]::Float, [Globalization.CultureInfo]::InvariantCulture, [ref]$duration) | Out-Null

    return $duration
}

function Get-FrameSeek {
    param([double]$Duration)

    if ($Duration -gt 0) {
        return [Math]::Max(20, [Math]::Min($Duration * 0.45, [Math]::Max(20, $Duration - 20)))
    }

    return 300
}

function Save-VideoFrame {
    param(
        [string]$Ffmpeg,
        [string]$InputPath,
        [string]$OutputPath,
        [double]$Seek,
        [int]$Width
    )

    if (Test-Path -LiteralPath $OutputPath) {
        return $true
    }

    if (!(Test-Path -LiteralPath $InputPath)) {
        return $false
    }

    & $Ffmpeg -y -ss (Format-VideoTimestamp $Seek) -i $InputPath -frames:v 1 -vf "scale=$($Width):-2" -q:v 3 $OutputPath 2>$null | Out-Null

    return Test-Path -LiteralPath $OutputPath
}

function Sync-EpisodeThumbnails {
    $root = Split-Path $PSScriptRoot -Parent
    $dataPath = Join-Path $root "data\series.js"

    if (!(Test-Path -LiteralPath $dataPath)) {
        return
    }

    $ffmpeg = Resolve-VideoTool (Get-BrasaEnvValue "FFMPEG_PATH") "ffmpeg"
    $ffprobe = Resolve-VideoTool (Get-BrasaEnvValue "FFPROBE_PATH") "ffprobe"

    if (!$ffmpeg) {
        Write-Host "BRasa: FFmpeg nao encontrado; thumbnails dos episodios nao foram gerados."
        return
    }

    $content = Get-Content -LiteralPath $dataPath -Raw -Encoding UTF8
    $match = [Text.RegularExpressions.Regex]::Match($content, "const seriesData = ([\s\S]*?);")

    if (!$match.Success) {
        Write-Host "BRasa: nao consegui ler data/series.js para gerar thumbnails."
        return
    }

    $series = $match.Groups[1].Value | ConvertFrom-Json
    $thumbDir = Join-Path $root "assets\episode-thumbnails"
    $backdropDir = Join-Path $root "assets\episode-backdrops"
    New-Item -ItemType Directory -Force -Path $thumbDir | Out-Null
    New-Item -ItemType Directory -Force -Path $backdropDir | Out-Null

    $changed = $false

    foreach ($item in @($series)) {
        foreach ($season in @($item.seasons)) {
            foreach ($episode in @($season.episodes)) {
                $fileName = "$(Get-Slug "$($item.id)-s$($episode.seasonNumber)-e$($episode.episodeNumber)").jpg"
                $thumbnailRelativePath = "assets/episode-thumbnails/$fileName"
                $backdropRelativePath = "assets/episode-backdrops/$fileName"
                $thumbnailOutputPath = Join-Path $root $thumbnailRelativePath
                $backdropOutputPath = Join-Path $root $backdropRelativePath
                $inputPath = Join-Path $root $episode.video

                $changed = (Set-BrasaProperty $episode "thumbnail" $thumbnailRelativePath) -or $changed
                $changed = (Set-BrasaProperty $episode "backdrop" $backdropRelativePath) -or $changed

                if (!(Test-Path -LiteralPath $inputPath)) {
                    continue
                }

                $duration = Get-VideoDuration $ffprobe $inputPath
                $seek = Get-FrameSeek $duration

                $thumbnailAlreadyExists = Test-Path -LiteralPath $thumbnailOutputPath
                if (Save-VideoFrame $ffmpeg $inputPath $thumbnailOutputPath $seek 640) {
                    if (!$thumbnailAlreadyExists) {
                        $changed = $true
                        Write-Host "BRasa: thumbnail gerada para `"$($item.title)`" T$($episode.seasonNumber)E$($episode.episodeNumber)."
                    }
                } else {
                    $episode.thumbnail = ""
                }

                $backdropAlreadyExists = Test-Path -LiteralPath $backdropOutputPath
                if (Save-VideoFrame $ffmpeg $inputPath $backdropOutputPath $seek 1280) {
                    if (!$backdropAlreadyExists) {
                        $changed = $true
                        Write-Host "BRasa: backdrop gerado para `"$($item.title)`" T$($episode.seasonNumber)E$($episode.episodeNumber)."
                    }
                } else {
                    $episode.backdrop = ""
                }
            }
        }
    }

    if ($changed) {
        Write-SeriesData $series
        Write-Host "BRasa: thumbnails de episodios vinculadas em data/series.js."
    }
}

function Sync-MovieBackdrops {
    $root = Split-Path $PSScriptRoot -Parent
    $dataPath = Join-Path $root "data\movies.js"

    if (!(Test-Path -LiteralPath $dataPath)) {
        return
    }

    $ffmpeg = Resolve-VideoTool (Get-BrasaEnvValue "FFMPEG_PATH") "ffmpeg"
    $ffprobe = Resolve-VideoTool (Get-BrasaEnvValue "FFPROBE_PATH") "ffprobe"

    if (!$ffmpeg) {
        Write-Host "BRasa: FFmpeg nao encontrado; backdrops de filmes nao foram gerados."
        return
    }

    $content = Get-Content -LiteralPath $dataPath -Raw -Encoding UTF8
    $match = [Text.RegularExpressions.Regex]::Match($content, "const movies = (\[[\s\S]*?\]);")

    if (!$match.Success) {
        Write-Host "BRasa: nao consegui ler data/movies.js para gerar backdrops."
        return
    }

    $movies = $match.Groups[1].Value | ConvertFrom-Json
    $backdropDir = Join-Path $root "assets\backdrops"
    New-Item -ItemType Directory -Force -Path $backdropDir | Out-Null

    $changed = $false

    foreach ($movie in @($movies)) {
        if (!$movie.video) {
            continue
        }

        $slugSource = if ($movie.imdbId) { "$($movie.title)-$($movie.year)-$($movie.imdbId)" } else { "$($movie.title)-$($movie.year)-$($movie.id)" }
        $fileName = "$(Get-Slug $slugSource).jpg"
        $relativePath = "assets/backdrops/$fileName"
        $outputPath = Join-Path $root $relativePath
        $inputPath = Join-Path $root $movie.video

        if (Test-Path -LiteralPath $outputPath) {
            $changed = (Set-BrasaProperty $movie "backdrop" $relativePath) -or $changed
            continue
        }

        if (!(Test-Path -LiteralPath $inputPath)) {
            continue
        }

        $duration = Get-VideoDuration $ffprobe $inputPath
        $seek = Get-FrameSeek $duration

        if (Save-VideoFrame $ffmpeg $inputPath $outputPath $seek 1280) {
            $changed = (Set-BrasaProperty $movie "backdrop" $relativePath) -or $changed
            $changed = $true
            Write-Host "BRasa: backdrop gerado para filme `"$($movie.title)`"."
        }
    }

    if ($changed) {
        Write-MoviesData $movies
        Write-Host "BRasa: backdrops de filmes vinculados em data/movies.js."
    }
}

Sync-EpisodeThumbnails
Sync-MovieBackdrops

exit $NodeExitCode
