package com.brasa.tv.feature.update
import com.brasa.tv.BuildConfig
import com.brasa.tv.core.model.ApiEnvelope
import com.brasa.tv.core.network.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import okhttp3.Request
interface UpdateApi{suspend fun check(baseUrl:String,client:UpdateClientInfo):UpdateCheckResponse}
class HttpUpdateApi(private val http:BrasaHttpClient,private val json:Json):UpdateApi{override suspend fun check(baseUrl:String,client:UpdateClientInfo)=withContext(Dispatchers.IO){val request=Request.Builder().url(LocalServerAddress.resolve(baseUrl,"/api/v1/android-tv/update")).header("Accept","application/json").header("X-BRasa-Client","brasa-android-tv").header("X-BRasa-Package-Name",BuildConfig.APPLICATION_ID).header("X-BRasa-Version-Code",client.versionCode.toString()).header("X-BRasa-Version-Name",client.versionName).header("X-BRasa-Client-Api","1").tag(AuthRequired::class.java,AuthRequired(true)).build();http.authenticatedClient().newCall(request).execute().use{response->val text=response.body.string();if(response.code==401)throw DeviceRevokedException();if(!response.isSuccessful)throw BrasaApiException(response.code,"Não foi possível consultar atualizações.");json.decodeFromString(ApiEnvelope.serializer(UpdateCheckResponse.serializer()),text).data?:error("Resposta de atualização vazia.")}}}
class UpdateRepository(private val api:UpdateApi,private val preferences:UpdateCheckCache,private val baseUrl:suspend()->String,private val now:()->Long={System.currentTimeMillis()},private val client:UpdateClientInfo=UpdateClientInfo(BuildConfig.VERSION_CODE.toLong(),BuildConfig.VERSION_NAME)){suspend fun check(force:Boolean=false):UpdateCheckResponse{if(!force&&preferences.lastCheckAt>0&&now()-preferences.lastCheckAt<24*60*60*1000)return visible(preferences.cachedResponse?:UpdateCheckResponse(),false);val base=baseUrl().ifBlank{error("Servidor BRasa não configurado.")};val result=api.check(base,client);preferences.lastCheckAt=now();preferences.cachedResponse=result;return visible(result,force)}fun defer(versionCode:Long){preferences.deferredVersionCode=versionCode}fun markInstalled(){preferences.cachedResponse=null;preferences.lastCheckAt=0;preferences.deferredVersionCode=0}fun lastCheckAt()=preferences.lastCheckAt;private fun visible(result:UpdateCheckResponse,force:Boolean):UpdateCheckResponse{val update=result.update;if(!result.available||update==null||update.versionCode<=client.versionCode)return UpdateCheckResponse(false);return if(!force&&update.versionCode==preferences.deferredVersionCode)UpdateCheckResponse(false)else result}}
