const ACTIVE_KEY = "brasa:active-profile", MIGRATION_KEY = "brasa:migration:profile-state-v2", PENDING_KEY = "brasa:pending-profile-writes";
const BACKOFF = [500, 1500, 5000], HISTORY_LIMIT = 500, FAVORITES_LIMIT = 5000;
const PREFERENCE_KEYS = new Set(["skipIntro", "skipCredits", "subtitleLanguage", "subtitleSize", "subtitleFont", "subtitleColor", "subtitleBackground", "subtitleOpacity", "subtitleOutline", "subtitlePosition", "subtitleSync", "audioLanguage", "maxVolume", "normalizeVolume", "preferSurround"]);
let profiles = [], states = new Map(), readyPromise = null, pendingWrites = [], profileWriteQueues = new Map();
let syncStatus = { pendingWrites: 0, failedWrites: 0, syncing: false, lastSavedAt: "", lastError: "" };

export function normalizeProfileState(input = {}) {
    const object = input && typeof input === "object" && !Array.isArray(input) ? input : {};
    const progress = object.progress && typeof object.progress === "object" && !Array.isArray(object.progress) ? { ...object.progress } : {};
    const preferences = object.preferences && typeof object.preferences === "object" && !Array.isArray(object.preferences) ? Object.fromEntries(Object.entries(object.preferences).filter(([key]) => PREFERENCE_KEYS.has(key))) : {};
    return { favorites: uniqueStrings(object.favorites).slice(0, FAVORITES_LIMIT), progress, history: Array.isArray(object.history) ? object.history.filter((item) => item && typeof item === "object").slice(0, HISTORY_LIMIT).map((item) => ({ ...item })) : [], completed: uniqueStrings(object.completed).slice(0, FAVORITES_LIMIT), preferences, updatedAt: validDateString(object.updatedAt) };
}
export function legacyProgressId(key) { return /^brasa:movie-progress:([^:]+)$/.exec(String(key || ""))?.[1] || ""; }
export function normalizeLegacyFavorites(value) { if (Array.isArray(value)) return uniqueStrings(value); if (value && typeof value === "object") return uniqueStrings(Object.entries(value).filter(([, enabled]) => enabled).map(([id]) => id)); return []; }
export function initializeProfileService() { if (!readyPromise) readyPromise = boot(); return readyPromise; }
export function listProfiles() { return profiles.map((profile) => ({ ...profile })); }
export function getActiveProfileRecord() { const id = localStorage.getItem(ACTIVE_KEY); return profiles.find((profile) => profile.id === id) || null; }
export function getCachedProfileState(id = getActiveProfileRecord()?.id) { return normalizeProfileState(states.get(id)); }
export function getProfileSyncStatus() { return { ...syncStatus }; }
export async function switchActiveProfile(id) { const profile = profiles.find((item) => item.id === id); if (!profile) throw new Error("Perfil inválido."); await loadState(id); localStorage.setItem(ACTIVE_KEY, id); document.dispatchEvent(new CustomEvent("brasa:profile-change", { detail: { profile } })); return profile; }
export async function createProfile(input) { const profile = await api("/api/profiles", { method: "POST", body: { ...input, id: createProfileId(input.name) } }); profiles.push(profile); states.set(profile.id, normalizeProfileState()); return profile; }
export async function updateProfile(id, input) { const profile = await api(`/api/profiles/${id}`, { method: "PUT", body: input }); profiles = profiles.map((item) => item.id === id ? profile : item); return profile; }
export async function removeProfile(id) { await api(`/api/profiles/${id}`, { method: "DELETE" }); profiles = profiles.filter((item) => item.id !== id); states.delete(id); }
export async function setProfilePin(id, pin, currentPin = "") { const result = await api(`/api/profiles/${id}/pin`, { method: "PUT", body: { pin, currentPin } }); profiles = profiles.map((profile) => profile.id === id ? { ...profile, hasPin: Boolean(pin) } : profile); return result; }
export async function verifyProfilePin(id, pin) { try { await api(`/api/profiles/${id}/verify-pin`, { method: "POST", body: { pin } }); return true; } catch { return false; } }
export function isFavoriteForActive(id) { return getCachedProfileState().favorites.includes(String(id)); }
export function setFavoriteForActive(id, value) { const profile = activeOrNeutral("favorite"); if (!profile) return false; const key = String(id), state = getCachedProfileState(profile.id); const favorites = value ? [...new Set([...state.favorites, key])].slice(0, FAVORITES_LIMIT) : state.favorites.filter((item) => item !== key); commitLocal(profile.id, { ...state, favorites }, "brasa:favorites-change"); enqueue({ profileId: profile.id, type: value ? "favorite-set" : "favorite-remove", mediaKey: key, url: `/api/profiles/${profile.id}/favorites/${encodeURIComponent(key)}`, method: value ? "PUT" : "DELETE" }); return value; }
export function getProgressForActive(key) { return getCachedProfileState().progress[key] || null; }
export function setProgressForActive(key, value) { const profile = activeOrNeutral("progress"); if (!profile) return null; const state = getCachedProfileState(profile.id), nextValue = { ...value }; const completed = nextValue.completed ? [...new Set([...state.completed, key])] : state.completed; commitLocal(profile.id, { ...state, progress: { ...state.progress, [key]: nextValue }, completed }, "brasa:progress-change"); enqueue({ profileId: profile.id, type: "progress-set", mediaKey: key, payload: nextValue, url: `/api/profiles/${profile.id}/progress/${encodeURIComponent(key)}`, method: "PUT" }); recordHistory({ mediaKey: key, mediaId: value.mediaId, title: value.title || "", completedAt: value.completed ? new Date().toISOString() : "" }); return nextValue; }
export function clearProgressForActive(key, { completed = false } = {}) { const profile = activeOrNeutral("progress-remove"); if (!profile) return false; const state = getCachedProfileState(profile.id), progress = { ...state.progress }; delete progress[key]; const completedItems = completed ? [...new Set([...state.completed, key])] : state.completed; commitLocal(profile.id, { ...state, progress, completed: completedItems }, "brasa:progress-change"); enqueue({ profileId: profile.id, type: "progress-remove", mediaKey: key, url: `/api/profiles/${profile.id}/progress/${encodeURIComponent(key)}`, method: "DELETE" }); return true; }
export function recordHistory(entry) { const profile = activeOrNeutral("history"); if (!profile || !entry?.mediaKey) return null; const state = getCachedProfileState(profile.id), now = new Date().toISOString(), item = { ...entry, operationId: entry.operationId || `${profile.id}:${entry.mediaKey}:${entry.startedAt || now}`, startedAt: entry.startedAt || now, lastWatchedAt: now }; const history = [item, ...state.history.filter((value) => value.mediaKey !== item.mediaKey)].slice(0, HISTORY_LIMIT); commitLocal(profile.id, { ...state, history }, "brasa:profile-state-change"); enqueue({ id: item.operationId, profileId: profile.id, type: "history-add", mediaKey: item.mediaKey, payload: item, url: `/api/profiles/${profile.id}/history`, method: "POST" }); return item; }
export function getProfilePreferences() { return { ...getCachedProfileState().preferences }; }
export function isCompletedForActive(key) { return getCachedProfileState().completed.includes(key); }
export function wasRecentlyWatchedForActive(key) { const entry = getCachedProfileState().history.find((item) => item.mediaKey === key); return entry ? Date.now() - (Date.parse(entry.lastWatchedAt) || 0) < 30 * 86400000 : false; }
export function saveProfilePreferences(values) { const profile = activeOrNeutral("preferences"); if (!profile) return false; const state = getCachedProfileState(profile.id), clean = Object.fromEntries(Object.entries(values || {}).filter(([key]) => PREFERENCE_KEYS.has(key))); const next = { ...state, preferences: { ...state.preferences, ...clean } }; commitLocal(profile.id, next, "brasa:preferences-change"); enqueue({ profileId: profile.id, type: "preferences-update", payload: clean, url: `/api/profiles/${profile.id}/state`, method: "PUT", body: next }); return true; }
export async function persistWholeState(id, state = getCachedProfileState(id)) { const normalized = normalizeProfileState(state); const saved = normalizeProfileState(await api(`/api/profiles/${id}/state`, { method: "PUT", body: normalized })); states.set(id, saved); return saved; }
export async function flushPendingProfileWrites() { const ids = [...new Set(pendingWrites.map((item) => item.profileId))]; await Promise.all(ids.map(processProfileQueue)); return getProfileSyncStatus(); }

async function boot() { loadPending(); try { profiles = await api("/api/profiles"); for (const profile of profiles) await loadState(profile.id); await migrateLegacy(); } catch (error) { profiles = fallbackProfiles(); for (const profile of profiles) states.set(profile.id, loadFallback(profile.id)); setSyncStatus({ lastError: error.message }); } await flushPendingProfileWrites(); return listProfiles(); }
async function loadState(id) { if (states.has(id)) return states.get(id); const state = normalizeProfileState(await api(`/api/profiles/${id}/state`)); states.set(id, state); return state; }
async function migrateLegacy() { if (localStorage.getItem(MIGRATION_KEY)) return; const state = getCachedProfileState("mario"), summary = { migratedFavorites: 0, migratedProgress: 0, skippedInvalid: 0, completedAt: "" }; try { let favorites = JSON.parse(localStorage.getItem("brasa:favorites") || "{}"); const values = Array.isArray(favorites) ? favorites : favorites && typeof favorites === "object" ? Object.entries(favorites).filter(([, value]) => value).map(([id]) => id) : []; const validFavorites = uniqueStrings(values); summary.migratedFavorites = validFavorites.filter((id) => !state.favorites.includes(id)).length; const progress = { ...state.progress }; for (let index = 0; index < localStorage.length; index++) { const key = localStorage.key(index), match = /^brasa:movie-progress:([^:]+)$/.exec(key || ""); if (!match) continue; try { const old = JSON.parse(localStorage.getItem(key) || "null"), duration = Number(old?.duration), currentTime = Number(old?.currentTime || 0); if (!old || !Number.isFinite(duration) || duration <= 0 || currentTime < 0) { summary.skippedInvalid++; continue; } progress[`movie:${match[1]}`] = { mediaType: "movie", mediaId: match[1], currentTime, duration, percentage: Math.min(100, Math.round(currentTime / duration * 100)), completed: false, updatedAt: validDateString(old.updatedAt) || new Date().toISOString() }; summary.migratedProgress++; } catch { summary.skippedInvalid++; } } let preferences = {}; try { preferences = profilePreferenceValues(JSON.parse(localStorage.getItem("brasa:preferences") || "{}")); } catch { summary.skippedInvalid++; } const next = normalizeProfileState({ ...state, favorites: [...new Set([...state.favorites, ...validFavorites])], progress, preferences: { ...state.preferences, ...preferences } }); await persistWholeState("mario", next); summary.completedAt = new Date().toISOString(); localStorage.setItem(MIGRATION_KEY, JSON.stringify(summary)); } catch (error) { setSyncStatus({ lastError: error.message }); } }
function commitLocal(id, state, event) { const normalized = normalizeProfileState({ ...state, updatedAt: new Date().toISOString() }); states.set(id, normalized); localStorage.setItem(`brasa:profile-cache:${id}`, JSON.stringify(normalized)); document.dispatchEvent(new CustomEvent(event, { detail: { profileId: id } })); }
function enqueue(input) { const operation = { id: input.id || `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`, profileId: input.profileId, type: input.type, mediaKey: input.mediaKey || "", payload: input.payload ?? input.body ?? null, url: input.url, method: input.method, body: input.body ?? input.payload, createdAt: new Date().toISOString(), attempts: 0 }; const existing = pendingWrites.findIndex((item) => item.profileId === operation.profileId && item.type === operation.type && item.mediaKey === operation.mediaKey && operation.type !== "history-add"); if (existing >= 0) pendingWrites[existing] = operation; else if (!pendingWrites.some((item) => item.id === operation.id)) pendingWrites.push(operation); savePending(); processProfileQueue(operation.profileId); return operation; }
function processProfileQueue(profileId) { if (profileWriteQueues.has(profileId)) return profileWriteQueues.get(profileId); const task = (async () => { setSyncStatus({ syncing: true }); let operation; while ((operation = pendingWrites.find((item) => item.profileId === profileId))) { let saved = false; for (let attempt = 0; attempt < BACKOFF.length; attempt++) { operation.attempts++; savePending(); try { await api(operation.url, { method: operation.method, body: operation.body }); saved = true; setSyncStatus({ lastSavedAt: new Date().toISOString(), lastError: "" }); break; } catch (error) { setSyncStatus({ lastError: error.message }); if (attempt < BACKOFF.length - 1) await delay(BACKOFF[attempt]); } } if (!saved) { setSyncStatus({ failedWrites: pendingWrites.filter((item) => item.attempts >= BACKOFF.length).length }); break; } pendingWrites = pendingWrites.filter((item) => item.id !== operation.id); savePending(); } })().finally(() => { profileWriteQueues.delete(profileId); setSyncStatus({ syncing: profileWriteQueues.size > 0 }); }); profileWriteQueues.set(profileId, task); return task; }
function loadPending() { try { const parsed = JSON.parse(localStorage.getItem(PENDING_KEY) || "[]"); pendingWrites = Array.isArray(parsed) ? parsed.filter((item) => item?.id && item?.profileId && item?.url) : []; } catch { pendingWrites = []; } setSyncStatus({ pendingWrites: pendingWrites.length }); }
function savePending() { localStorage.setItem(PENDING_KEY, JSON.stringify(pendingWrites)); setSyncStatus({ pendingWrites: pendingWrites.length }); }
function setSyncStatus(patch) { syncStatus = { ...syncStatus, ...patch, pendingWrites: pendingWrites.length }; document.dispatchEvent(new CustomEvent("brasa:profile-sync-status", { detail: { ...syncStatus } })); }
function activeOrNeutral(action) { const profile = getActiveProfileRecord(); if (!profile && globalThis.BRASA_DEBUG) console.warn(`BRasa: operação ${action} ignorada sem perfil ativo.`); return profile; }
function loadFallback(id) { try { return normalizeProfileState(JSON.parse(localStorage.getItem(`brasa:profile-cache:${id}`) || "null")); } catch { return normalizeProfileState(); } }
function fallbackProfiles() { return [{ id: "mario", name: "Mário", initials: "M", kind: "adult", avatar: { color: "blue" } }, { id: "isabele", name: "Isabele", initials: "I", kind: "adult", avatar: { color: "purple" } }, { id: "laura", name: "Laura", initials: "L", kind: "kids", maxContentRating: 10, avatar: { color: "pink" } }]; }
function createProfileId(name) { const base = String(name || "perfil").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 32) || "perfil"; return `${base}-${Date.now().toString(36)}`; }
function profilePreferenceValues(input) { const value = input && typeof input === "object" ? input : {}; return Object.fromEntries(Object.entries(value).filter(([key]) => PREFERENCE_KEYS.has(key))); }
function uniqueStrings(value) { return Array.isArray(value) ? [...new Set(value.filter((item) => typeof item === "string" && item.length <= 160))] : []; }
function validDateString(value) { return typeof value === "string" && Number.isFinite(Date.parse(value)) ? value : ""; }
const delay = (value) => new Promise((resolve) => setTimeout(resolve, value));
async function api(url, options = {}) { const headers = { "X-BRasa-Request": "1", ...(options.body ? { "Content-Type": "application/json" } : {}) }; const response = await fetch(url, { method: options.method || "GET", headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "Não foi possível acessar os perfis."); return data.profile ?? data.profiles ?? data.state ?? data; }
