const ACTIVE_KEY="brasa:active-profile";const MIGRATION_KEY="brasa:migration:profile-state-v1";let profiles=[];let states=new Map();let readyPromise=null;
export function initializeProfileService(){if(!readyPromise)readyPromise=boot();return readyPromise;}
export function listProfiles(){return profiles.map((p)=>({...p}));}
export function getActiveProfileRecord(){const id=localStorage.getItem(ACTIVE_KEY);return profiles.find((p)=>p.id===id)||null;}
export function getCachedProfileState(id=getActiveProfileRecord()?.id){return states.get(id)||emptyState();}
export async function switchActiveProfile(id){const profile=profiles.find((p)=>p.id===id);if(!profile)throw new Error("Perfil inválido.");await loadState(id);localStorage.setItem(ACTIVE_KEY,id);document.dispatchEvent(new CustomEvent("brasa:profile-change",{detail:{profile}}));return profile;}
export async function createProfile(input){const profile=await api("/api/profiles",{method:"POST",body:{...input,id:createProfileId(input.name)}});profiles.push(profile);states.set(profile.id,emptyState());return profile;}
export async function updateProfile(id,input){const profile=await api(`/api/profiles/${id}`,{method:"PUT",body:input});profiles=profiles.map((p)=>p.id===id?profile:p);return profile;}
export async function removeProfile(id){await api(`/api/profiles/${id}`,{method:"DELETE"});profiles=profiles.filter((p)=>p.id!==id);states.delete(id);}
export async function setProfilePin(id,pin){return api(`/api/profiles/${id}/pin`,{method:"PUT",body:{pin}});}
export async function verifyProfilePin(id,pin){try{await api(`/api/profiles/${id}/verify-pin`,{method:"POST",body:{pin}});return true;}catch{return false;}}
export function isFavoriteForActive(id){return getCachedProfileState().favorites.includes(String(id));}
export function setFavoriteForActive(id,value){const profile=getActiveProfileRecord();const state=getCachedProfileState();const key=String(id);state.favorites=value?[...new Set([...state.favorites,key])]:state.favorites.filter((item)=>item!==key);touch(profile.id,state,"brasa:favorites-change");api(`/api/profiles/${profile.id}/favorites/${encodeURIComponent(key)}`,{method:value?"PUT":"DELETE"}).catch(()=>{});return value;}
export function getProgressForActive(key){return getCachedProfileState().progress[key]||null;}
export function setProgressForActive(key,value){const profile=getActiveProfileRecord();const state=getCachedProfileState();state.progress[key]=value;if(value.completed){state.completed=[...new Set([...state.completed,key])];}touch(profile.id,state,"brasa:progress-change");api(`/api/profiles/${profile.id}/progress/${encodeURIComponent(key)}`,{method:"PUT",body:value}).catch(()=>{});recordHistory({mediaKey:key,mediaId:value.mediaId,title:value.title||"",completedAt:value.completed?new Date().toISOString():""});}
export function clearProgressForActive(key,{completed=false}={}){const profile=getActiveProfileRecord();const state=getCachedProfileState();delete state.progress[key];if(completed)state.completed=[...new Set([...state.completed,key])];touch(profile.id,state,"brasa:progress-change");api(`/api/profiles/${profile.id}/progress/${encodeURIComponent(key)}`,{method:"DELETE"}).catch(()=>{});}
export function recordHistory(entry){const profile=getActiveProfileRecord();if(!profile)return;const state=getCachedProfileState();const now=new Date().toISOString();const item={...entry,startedAt:entry.startedAt||now,lastWatchedAt:now};state.history=[item,...state.history.filter((h)=>h.mediaKey!==item.mediaKey)].slice(0,500);touch(profile.id,state,"brasa:profile-state-change");api(`/api/profiles/${profile.id}/history`,{method:"POST",body:item}).catch(()=>{});}
export function getProfilePreferences(){return {...getCachedProfileState().preferences};}
export function isCompletedForActive(key){return getCachedProfileState().completed.includes(key);}
export function wasRecentlyWatchedForActive(key){const entry=getCachedProfileState().history.find((item)=>item.mediaKey===key);return entry?Date.now()-(Date.parse(entry.lastWatchedAt)||0)<30*86400000:false;}
export function saveProfilePreferences(values){const profile=getActiveProfileRecord();const state=getCachedProfileState();state.preferences={...state.preferences,...values};touch(profile.id,state,"brasa:preferences-change");persistWholeState(profile.id,state).catch(()=>{});}
export async function persistWholeState(id,state=getCachedProfileState(id)){const saved=await api(`/api/profiles/${id}/state`,{method:"PUT",body:state});states.set(id,saved);return saved;}
async function boot(){try{profiles=await api("/api/profiles");for(const p of profiles)await loadState(p.id);await migrateLegacy();}catch{profiles=fallbackProfiles();for(const p of profiles)states.set(p.id,loadFallback(p.id));}return listProfiles();}
async function loadState(id){if(states.has(id))return states.get(id);const state=await api(`/api/profiles/${id}/state`);states.set(id,state);return state;}
async function migrateLegacy(){if(localStorage.getItem(MIGRATION_KEY))return;const state=getCachedProfileState("mario");try{const favorites=JSON.parse(localStorage.getItem("brasa:favorites")||"{}");Object.entries(favorites).forEach(([id,value])=>{if(value&&!state.favorites.includes(id))state.favorites.push(id);});for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith("brasa:movie-progress:"))continue;const id=key.slice("brasa:movie-progress:".length);const old=JSON.parse(localStorage.getItem(key)||"{}");if(old.duration)state.progress[`movie:${id}`]={mediaType:"movie",mediaId:id,currentTime:Number(old.currentTime||0),duration:Number(old.duration),percentage:Math.round(Number(old.currentTime||0)/Number(old.duration)*100),completed:false,updatedAt:old.updatedAt||new Date().toISOString()};}const prefs=JSON.parse(localStorage.getItem("brasa:preferences")||"{}");state.preferences={...state.preferences,...profilePreferenceValues(prefs)};await persistWholeState("mario",state);localStorage.setItem(MIGRATION_KEY,new Date().toISOString());}catch{/* keep legacy data and retry later */}}
function touch(id,state,event){state.updatedAt=new Date().toISOString();states.set(id,state);localStorage.setItem(`brasa:profile-cache:${id}`,JSON.stringify(state));document.dispatchEvent(new CustomEvent(event,{detail:{profileId:id}}));}
function loadFallback(id){try{return JSON.parse(localStorage.getItem(`brasa:profile-cache:${id}`)||"null")||emptyState();}catch{return emptyState();}}
function emptyState(){return {favorites:[],progress:{},history:[],completed:[],preferences:{},updatedAt:""};}
function fallbackProfiles(){return [{id:"mario",name:"Mário",initials:"M",kind:"adult",avatar:{color:"blue"}},{id:"isabele",name:"Isabele",initials:"I",kind:"adult",avatar:{color:"purple"}},{id:"laura",name:"Laura",initials:"L",kind:"kids",avatar:{color:"pink"}}];}
function createProfileId(name){const base=String(name||"perfil").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,32)||"perfil";return `${base}-${Date.now().toString(36)}`;}
function profilePreferenceValues(p){const keys=["skipIntro","skipCredits","subtitleLanguage","subtitleSize","subtitleFont","subtitleColor","subtitleBackground","subtitleOpacity","subtitleOutline","subtitlePosition","subtitleSync","audioLanguage","maxVolume","normalizeVolume","preferSurround"];return Object.fromEntries(keys.filter((k)=>k in p).map((k)=>[k,p[k]]));}
async function api(url,options={}){const response=await fetch(url,{method:options.method||"GET",headers:options.body?{"Content-Type":"application/json"}:undefined,body:options.body?JSON.stringify(options.body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Não foi possível acessar os perfis.");return data.profile??data.profiles??data.state??data;}
